name: "Terraform-Apply-Infra-Release"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    defaults:
      run:
      # specify the target folder here working directory.
        working-directory: acsal_uat


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

          # use this to cinfigure your working folder
        id: filter
        with:
          filters: |
            acsal_uat:
              - 'acsal_uat/module**
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt  

      - name: Terraform Validate
        run: terraform validate
  
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply --auto-approve
